-- Generated by supabase/seed/build.ts from supabase/seed/catalogue.ts. Do not edit by hand: run `pnpm db:seed`.
-- Loaded by `supabase db reset` after the migrations. Demo data only; the reference catalogue is a migration.

insert into public.partners (id, name, kind, contact_email) values
  ($t$6f1c5d3e-0000-4000-8000-000000000001$t$, $t$Greenhouse Growers$t$, $t$grower$t$, $t$growers@example.com$t$)
on conflict do nothing;

insert into public.qr_codes (code, partner_id, species_id, cultivar, status) values
  ($t$PL-0001$t$, $t$6f1c5d3e-0000-4000-8000-000000000001$t$, (select id from public.species where slug = $t$peace-lily$t$), null, $t$active$t$)
on conflict do nothing;
