// Writes supabase/seed.sql from supabase/seed/catalogue.ts. Run it with `pnpm db:seed` and commit the output.
//
// Statement order matters: sensitive taxa come before species because a trigger flags each species as sensitive
// while it is inserted. Every text value is dollar-quoted, so apostrophes need no escaping, and every insert is
// `on conflict do nothing`, so loading the seed twice is harmless.

import { aoife } from '../../packages/core/src/fixtures/aoife.ts';
import {
  partners,
  qrCodes,
  sensitiveTaxa,
  sets,
  speciesSeeds,
  toxicitySeeds,
} from './catalogue.ts';

function text(value: string): string {
  // No catalogue value needs a dollar sign. Refusing them all rules out a value that ends the quote early.
  if (value.includes('$')) throw new Error(`seed values cannot contain "$": ${value}`);
  return `$t$${value}$t$`;
}

const nullableText = (value: string | null | undefined) =>
  value === null || value === undefined ? 'null' : text(value);
const nullableNumber = (value: number | null | undefined) =>
  value === null || value === undefined ? 'null' : String(value);
const speciesId = (slug: string) => `(select id from public.species where slug = ${text(slug)})`;

function insert(table: string, columns: string[], rows: string[]): string {
  const values = rows.map((row) => `  (${row})`).join(',\n');
  return `insert into ${table} (${columns.join(', ')}) values\n${values}\non conflict do nothing;`;
}

/** Fails the build on data that the database would reject, or that has drifted from the UX brief's fixture. */
function validate(): void {
  const fail = (message: string): never => {
    throw new Error(`seed catalogue: ${message}`);
  };
  const slugs = new Set<string>();
  const scientificNames = new Set<string>();
  for (const s of speciesSeeds) {
    if (!/^[a-z0-9-]+$/.test(s.slug)) fail(`bad slug "${s.slug}"`);
    if (slugs.has(s.slug)) fail(`duplicate slug "${s.slug}"`);
    if (scientificNames.has(s.scientificName))
      fail(`duplicate scientific name "${s.scientificName}"`);
    slugs.add(s.slug);
    scientificNames.add(s.scientificName);
    const c = s.care;
    if (c) {
      const inRange = (n: number) => Number.isInteger(n) && n >= 1 && n <= 3;
      if (!inRange(c.wateringMin) || !inRange(c.wateringMax) || c.wateringMin > c.wateringMax) {
        fail(`bad watering range for "${s.slug}"`);
      }
      if (
        c.checkIntervalDays !== undefined &&
        (c.checkIntervalDays < 2 || c.checkIntervalDays > 30)
      ) {
        fail(`bad check interval for "${s.slug}"`);
      }
    }
  }

  for (const [slug, entries] of Object.entries(toxicitySeeds)) {
    if (!slugs.has(slug)) fail(`toxicity for unknown species "${slug}"`);
    const animals = entries.map((e) => e.animal).sort();
    if (new Set(animals).size !== animals.length) fail(`"${slug}" repeats an animal`);
    for (const e of entries) {
      if (!e.sourceName || !e.sourceUrl) fail(`"${slug}" ${e.animal} row has no source`);
    }
  }
  for (const set of sets) {
    for (const slug of set.speciesSlugs) {
      if (!slugs.has(slug)) fail(`set "${set.id}" names unknown species "${slug}"`);
    }
  }
  const partnerIds = new Set(partners.map((p) => p.id));
  for (const q of qrCodes) {
    if (!/^[A-Z0-9-]{4,32}$/.test(q.code)) fail(`bad label code "${q.code}"`);
    if (!partnerIds.has(q.partnerId)) fail(`label "${q.code}" names an unknown partner`);
    if (!slugs.has(q.speciesSlug))
      fail(`label "${q.code}" names unknown species "${q.speciesSlug}"`);
  }

  // The fixture is the UX brief's sample data: the catalogue must carry every one of its species unchanged,
  // and must agree with each toxicity verdict the fixture has actually reached.
  for (const [slug, ref] of Object.entries(aoife.species)) {
    const seeded = speciesSeeds.find((s) => s.slug === slug);
    if (!seeded) fail(`fixture species "${slug}" is missing from the catalogue`);
    else if (
      seeded.commonName !== ref.commonName ||
      seeded.scientificName !== ref.scientificName ||
      seeded.rarity !== ref.rarity
    ) {
      fail(`"${slug}" differs from the fixture`);
    }
  }
  for (const [slug, entries] of Object.entries(aoife.speciesToxicity)) {
    for (const entry of entries) {
      if (entry.severity === 'unknown') continue;
      const seeded = toxicitySeeds[slug]?.find((e) => e.animal === entry.animal);
      if (seeded?.severity !== entry.severity) {
        fail(`"${slug}" ${entry.animal} toxicity differs from the fixture`);
      }
    }
  }
}

export function buildSeedSql(): string {
  validate();

  const statements: string[] = [
    [
      '-- Generated by supabase/seed/build.ts from supabase/seed/catalogue.ts. Do not edit by hand: run `pnpm db:seed`.',
      '-- Loaded by `supabase db reset`. Every toxicity row awaits vet review (seed_pending_vet).',
    ].join('\n'),
  ];

  statements.push(
    insert(
      'private.sensitive_taxa',
      ['rank', 'taxon', 'reason', 'source'],
      sensitiveTaxa.map((t) =>
        [t.rank, t.taxon, t.reason, t.source].map((value) => text(value)).join(', '),
      ),
    ),
  );

  statements.push(
    insert(
      'public.species',
      [
        'slug',
        'scientific_name',
        'common_name',
        'family',
        'genus',
        'is_houseplant',
        'watering_min',
        'watering_max',
        'light',
        'check_interval_days',
        'warmth',
        'rarity_tier',
      ],
      speciesSeeds.map((s) =>
        [
          text(s.slug),
          text(s.scientificName),
          text(s.commonName),
          text(s.family),
          text(s.genus),
          String(s.care !== null),
          nullableNumber(s.care?.wateringMin),
          nullableNumber(s.care?.wateringMax),
          nullableText(s.care?.light),
          nullableNumber(s.care?.checkIntervalDays),
          nullableText(s.care?.warmth),
          text(s.rarity),
        ].join(', '),
      ),
    ),
  );

  statements.push(
    insert(
      'public.species_toxicity',
      [
        'species_id',
        'animal',
        'severity',
        'summary',
        'symptoms',
        'source_name',
        'source_url',
        'review_status',
      ],
      Object.entries(toxicitySeeds).flatMap(([slug, entries]) =>
        entries.map((e) =>
          [
            speciesId(slug),
            text(e.animal),
            text(e.severity),
            nullableText(e.summary),
            nullableText(e.symptoms),
            text(e.sourceName),
            text(e.sourceUrl),
            text('seed_pending_vet'),
          ].join(', '),
        ),
      ),
    ),
  );

  statements.push(
    insert(
      'public.partners',
      ['id', 'name', 'kind', 'contact_email'],
      partners.map((p) =>
        [p.id, p.name, p.kind, p.contactEmail].map((value) => text(value)).join(', '),
      ),
    ),
  );

  statements.push(
    insert(
      'public.qr_codes',
      ['code', 'partner_id', 'species_id', 'cultivar', 'status'],
      qrCodes.map((q) =>
        [
          text(q.code),
          text(q.partnerId),
          speciesId(q.speciesSlug),
          nullableText(q.cultivar),
          text('active'),
        ].join(', '),
      ),
    ),
  );

  return statements.join('\n\n') + '\n';
}

if (import.meta.main) {
  Deno.writeTextFileSync(new URL('../seed.sql', import.meta.url), buildSeedSql());
}
